#!/bin/sh


ARITH="./arith.c"
gcc ${ARITH} -Darithoh -o "./capsicum_pgms/arith"
gcc ${ARITH} -Ddatum='register int' -o "./capsicum_pgms/register"
gcc $ARITH -Ddatum='short' -o "./capsicum_pgms/short"
gcc $ARITH -Ddatum='int' -o "./capsicum_pgms/int"
gcc $ARITH -Ddatum='long' -o "./capsicum_pgms/long"
gcc $ARITH -Ddatum='float' -o "./capsicum_pgms/float"
gcc $ARITH -Ddatum='double' -o "./capsicum_pgms/double"

gcc "./time-polling.c" -DUNIXBENCH -DHAS_POLL -o "./capsicum_pgms/poll"
gcc "./time-polling.c" -DUNIXBENCH -DHAS_POLL2 -o "./capsicum_pgms/poll2"
gcc "./time-polling.c" -DUNIXBENCH -DHAS_SELECT -o "./capsicum_pgms/select"

gcc "./whets.c" -DDP -DGTODay -DUNIXBENCH -lm -o "./capsicum_pgms/whetstone-double"

gcc "./pipe.c" -o "./capsicum_pgms/pipe"

gcc "./execl.c" -o "./capsicum_pgms/execl"

gcc "spawn.c" -o "./capsicum_pgms/spawn"

gcc "./fstime.c"  -o "./capsicum_pgms/fstime"

gcc "./syscall.c" -o "./capsicum_pgms/syscall"

gcc "./context1.c" -o "./capsicum_pgms/context1"

gcc "./looper.c" -o "./capsicum_pgms/looper"

gcc "./dhry_1.c" "./dhry_2.c" -DHZ=${HZ} -o "./capsicum_pgms/dhry2"

gcc "./dhry_1.c" "./dhry_2.c" -DHZ=${HZ} -DREG='register' -o "./capsicum_pgms/dhry2reg"
